<?php

declare(strict_types=1);

namespace Pozys\SpaceBattle\Plugins;

use Pozys\SpaceBattle\Container;
use Pozys\SpaceBattle\Core\InterfaceAdapterGenerator;
use Pozys\SpaceBattle\Interfaces\GameObjectInterface;
use Pozys\SpaceBattle\Interfaces\MovingInterface;

class MovingPlugin
{
    public static function load(): void
    {
        Container::resolve(
            'IoC.Register',
            'Adapter',
            function (GameObjectInterface $object): MovingInterface {
                $className = 'AutoGeneratedMovingInterfaceAdapter';

                eval((new InterfaceAdapterGenerator(MovingInterface::class, $className))->generate());

                return new $className($object);
            }
        );
    }
}
